version: "2.1"

services:
  php:
    build: bin/.
    volumes:
      - ./bin/:/var/www/html
    ports:
      - 80:80
    networks:
      - default
    environment:
      DB_HOST: db
      DB_DATABASE: enthraler
      DB_USERNAME: root
      DB_PASSWORD: root

  # Database
  db:
    image: mysql:5.7
    environment:
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - database:/var/lib/mysql

  # PhpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    networks:
      - default
    ports:
      - 8181:80
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: root
      PHP_UPLOAD_MAX_FILESIZE: 1000M

volumes:
  database:

networks:
  default:
    driver: bridge
